name: cicddev
on:
  push:
    branches: dev
jobs:
  runs-on: ubuntu-20.04
    steps:
    - name: checkout branch
      uses: actions/checkout@v4

    - name: setup node
      uses: actions/setup-node@v4
      with:
        node-version: '20'

    - name: node modules install
      run: npm install

    - name: to build the code
      run: npm run build

    - name: upload to s3 bucket
      uses: jakejarvis/s3-sync-action@master
      env:
        AWS_S3_BUCKET: '${{ secrets.DEV_S3_LINK}}'
        AWS_ACCESS_KEY_ID: '${{ secrets.ACCESS_KEY_ID }}'
        AWS_SECRET_ACCESS_KEY: '${{ secrets.SCRECT_KEY }}'
        AWS_REGION: us-east-1
        SOURCE_DIR: dist
