name: cicddev

on:
  push:
    branches:
      - dev

jobs:
      build:
        runs-on: ubuntu-20.04
        steps:
        - name: Checkout branch
          uses: actions/checkout@v4
          
        - name: Setup Node.js
          uses: actions/setup-node@v4
          with:
            node-version: '20'
  
        - name: Install Node modules
          run: npm install
  
        - name: Build the code
          run: npm run build
  
        - name: Upload to S3 bucket
          uses: jakejarvis/s3-sync-action@master
          env:
            AWS_S3_BUCKET: ${{ secrets.DEV_S3_LINK }}
            AWS_ACCESS_KEY_ID: ${{ secrets.ACCESS_KEY_ID }}
            AWS_SECRET_ACCESS_KEY: ${{ secrets.SECRET_KEY }}
            AWS_REGION: us-east-1
            SOURCE_DIR: dist
